from typing import TYPE_CHECKING


# setting values for type checking
if TYPE_CHECKING:
    K_0: int
    K_1: int
    K_2: int
    K_3: int
    K_4: int
    K_5: int
    K_6: int
    K_7: int
    K_8: int
    K_9: int
    K_AC_BACK: int
    K_AMPERSAND: int
    K_ASTERISK: int
    K_AT: int
    K_BACKQUOTE: int
    K_BACKSLASH: int
    K_BACKSPACE: int
    K_BREAK: int
    K_CAPSLOCK: int
    K_CARET: int
    K_CLEAR: int
    K_COLON: int
    K_COMMA: int
    K_CURRENCYSUBUNIT: int
    K_CURRENCYUNIT: int
    K_DELETE: int
    K_DOLLAR: int
    K_DOWN: int
    K_END: int
    K_EQUALS: int
    K_ESCAPE: int
    K_EURO: int
    K_EXCLAIM: int
    K_F1: int
    K_F10: int
    K_F11: int
    K_F12: int
    K_F13: int
    K_F14: int
    K_F15: int
    K_F2: int
    K_F3: int
    K_F4: int
    K_F5: int
    K_F6: int
    K_F7: int
    K_F8: int
    K_F9: int
    K_GREATER: int
    K_HASH: int
    K_HELP: int
    K_HOME: int
    K_INSERT: int
    K_KP0: int
    K_KP1: int
    K_KP2: int
    K_KP3: int
    K_KP4: int
    K_KP5: int
    K_KP6: int
    K_KP7: int
    K_KP8: int
    K_KP9: int
    K_KP_0: int
    K_KP_1: int
    K_KP_2: int
    K_KP_3: int
    K_KP_4: int
    K_KP_5: int
    K_KP_6: int
    K_KP_7: int
    K_KP_8: int
    K_KP_9: int
    K_KP_DIVIDE: int
    K_KP_ENTER: int
    K_KP_EQUALS: int
    K_KP_MINUS: int
    K_KP_MULTIPLY: int
    K_KP_PERIOD: int
    K_KP_PLUS: int
    K_LALT: int
    K_LCTRL: int
    K_LEFT: int
    K_LEFTBRACKET: int
    K_LEFTPAREN: int
    K_LESS: int
    K_LGUI: int
    K_LMETA: int
    K_LSHIFT: int
    K_LSUPER: int
    K_MENU: int
    K_MINUS: int
    K_MODE: int
    K_NUMLOCK: int
    K_NUMLOCKCLEAR: int
    K_PAGEDOWN: int
    K_PAGEUP: int
    K_PAUSE: int
    K_PERCENT: int
    K_PERIOD: int
    K_PLUS: int
    K_POWER: int
    K_PRINT: int
    K_PRINTSCREEN: int
    K_QUESTION: int
    K_QUOTE: int
    K_QUOTEDBL: int
    K_RALT: int
    K_RCTRL: int
    K_RETURN: int
    K_RGUI: int
    K_RIGHT: int
    K_RIGHTBRACKET: int
    K_RIGHTPAREN: int
    K_RMETA: int
    K_RSHIFT: int
    K_RSUPER: int
    K_SCROLLLOCK: int
    K_SCROLLOCK: int
    K_SEMICOLON: int
    K_SLASH: int
    K_SPACE: int
    K_SYSREQ: int
    K_TAB: int
    K_UNDERSCORE: int
    K_UNKNOWN: int
    K_UP: int
    K_a: int
    K_b: int
    K_c: int
    K_d: int
    K_e: int
    K_f: int
    K_g: int
    K_h: int
    K_i: int
    K_j: int
    K_k: int
    K_l: int
    K_m: int
    K_n: int
    K_o: int
    K_p: int
    K_q: int
    K_r: int
    K_s: int
    K_t: int
    K_u: int
    K_v: int
    K_w: int
    K_x: int
    K_y: int
    K_z: int