name: Create Release

on:
  push:
    tags:
      - v*
    branches: 
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: PyGreenfoot Module (${{ github.ref_name }})
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
