name: Create Release

on:
  push:
    tags:
      - v*
    branches: 
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install zip
      - run: zip -r pygreenfoot.zip pygreenfoot
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: PyGreenfoot Module (${{ github.ref_name }})
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Add package folder
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pygreenfoot.zip
          asset_name: pygreenfoot-${{ github.ref_name }}
          asset_content_type: application/zip
